alias gs='git status -sb'
alias gl='git pull --rebase'
alias gb='git checkout -b'
alias home="cd ~"
alias vaitimao="zzfutebol | grep Corinthians"
alias timaonobrasileirao="zzbrasileirao | grep Corinthians"
alias reload!="source $HOME/.bashrc"
alias zzcpfx="zzcpf | xclip -selection c"
alias zzcnpjx="zzcnpj | xclip -selection c"
alias b="cd .."
alias projects="cd $HOME/projects"
alias mybashfiles="cd $HOME/.mybashfiles"
